/*************************************************/
--------AGREGAR COLUMNA FLAG A TABLAS INT----------
/*************************************************/

ALTER TABLE [DW_COMERCIAL].[dbo].INT_DIM_CATEGORIA ADD FLAG varchar(2) 
ALTER TABLE [DW_COMERCIAL].[dbo].INT_DIM_PRODUCTO ADD FLAG varchar(2)
ALTER TABLE [DW_COMERCIAL].[dbo].INT_DIM_CLIENTE ADD FLAG varchar(2)
ALTER TABLE [DW_COMERCIAL].[dbo].INT_DIM_PAIS ADD FLAG varchar(2)
ALTER TABLE [DW_COMERCIAL].[dbo].INT_DIM_VENDEDOR ADD FLAG varchar(2)
ALTER TABLE [DW_COMERCIAL].[dbo].INT_DIM_SUCURSAL ADD FLAG varchar(2)
ALTER TABLE [DW_COMERCIAL].[dbo].INT_FACT_VENTAS ADD FLAG varchar(2)

/*************************************************/
----------ESTABLECER RELACIONES FACT VENTAS-------
/*************************************************/

ALTER TABLE [DW_COMERCIAL].[dbo].[FACT_VENTAS]
ADD CONSTRAINT FK_CATEGORIA
FOREIGN KEY (CATEGORIA_KEY)
REFERENCES [DW_COMERCIAL].[dbo].DIM_CATEGORIA (CATEGORIA_KEY)

ALTER TABLE [DW_COMERCIAL].[dbo].[FACT_VENTAS]
ADD CONSTRAINT FK_CLIENTE
FOREIGN KEY (CLIENTE_KEY)
REFERENCES [DW_COMERCIAL].[dbo].DIM_CLIENTE (CLIENTE_KEY)

ALTER TABLE [DW_COMERCIAL].[dbo].[FACT_VENTAS]
ADD CONSTRAINT FK_PAIS
FOREIGN KEY (PAIS_KEY)
REFERENCES [DW_COMERCIAL].[dbo].DIM_PAIS (PAIS_KEY)

ALTER TABLE [DW_COMERCIAL].[dbo].[FACT_VENTAS]
ADD CONSTRAINT FK_VENDEDOR
FOREIGN KEY (VENDEDOR_KEY)
REFERENCES [DW_COMERCIAL].[dbo].DIM_VENDEDOR (VENDEDOR_KEY)

ALTER TABLE [DW_COMERCIAL].[dbo].[FACT_VENTAS]
ADD CONSTRAINT FK_SUCURSAL
FOREIGN KEY (SUCURSAL_KEY)
REFERENCES [DW_COMERCIAL].[dbo].DIM_SUCURSAL (SUCURSAL_KEY)

ALTER TABLE [DW_COMERCIAL].[dbo].[FACT_VENTAS]
ADD CONSTRAINT FK_TIEMPO
FOREIGN KEY (TIEMPO_KEY)
REFERENCES [DW_COMERCIAL].[dbo].DIM_TIEMPO (TIEMPO_KEY)

ALTER TABLE [DW_COMERCIAL].[dbo].[FACT_VENTAS]
ADD CONSTRAINT FK_PRODUCTO
FOREIGN KEY (PRODUCTO_KEY)
REFERENCES [DW_COMERCIAL].[dbo].DIM_PRODUCTO (PRODUCTO_KEY)

