USE [DW_COMERCIAL]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[sp_carga_int_DIM_PAIS]
AS
BEGIN

TRUNCATE TABLE[DW_COMERCIAL].[dbo].INT_DIM_PAIS 

INSERT INTO [DW_COMERCIAL].[dbo].INT_DIM_PAIS (
    COD_PAIS, DESC_PAIS, FLAG
)
SELECT COD_PAIS, DESC_PAIS,
    CASE 
    WHEN rep > 1 OR flag = '-1' THEN 'N'
    ELSE 'S' 
    END AS FLAG 
FROM(SELECT COD_PAIS, DESC_PAIS,
    CASE 
    WHEN [COD_PAIS] IS NULL OR [DESC_PAIS] IS NULL
    THEN '-1'
    ELSE '1'
    END AS flag,
    ROW_NUMBER() OVER ( PARTITION BY COD_PAIS, DESC_PAIS ORDER BY COD_PAIS DESC) AS rep
FROM [DW_COMERCIAL].[dbo].STG_DIM_PAIS) AS SUB

END