USE [DW_COMERCIAL]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[sp_carga_int_DIM_PRODUCTO]
AS
BEGIN

TRUNCATE TABLE [DW_COMERCIAL].[dbo].INT_DIM_PRODUCTO 
INSERT INTO [DW_COMERCIAL].[dbo].INT_DIM_PRODUCTO(
    COD_PRODUCTO, DESC_PRODUCTO, FLAG
)

SELECT COD_PRODUCTO, DESC_PRODUCTO,
    CASE 
    WHEN rep > 1 OR flag = '-1' THEN 'N'
    ELSE 'S' 
    END AS FLAG

FROM (
    SELECT COD_PRODUCTO, DESC_PRODUCTO,
    CASE 
    WHEN [DESC_PRODUCTO] IS NULL OR [COD_PRODUCTO] IS NULL
    THEN '-1'
    ELSE '1'
    END AS flag,
    ROW_NUMBER() OVER ( PARTITION BY COD_PRODUCTO, DESC_PRODUCTO ORDER BY COD_PRODUCTO DESC) AS rep
    FROM [DW_COMERCIAL].[dbo].STG_DIM_PRODUCTO) AS sub

END