USE [DW_COMERCIAL]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[sp_carga_int_DIM_SUCURSAL]
AS
BEGIN

TRUNCATE TABLE [DW_COMERCIAL].[dbo].INT_DIM_SUCURSAL

INSERT INTO [DW_COMERCIAL].[dbo].INT_DIM_SUCURSAL(
    COD_SUCURSAL, DESC_SUCURSAL, FLAG
)
SELECT COD_SUCURSAL, DESC_SUCURSAL, 
    CASE 
    WHEN rep > 1 OR flag = '-1' THEN 'N'
    ELSE 'S' 
    END AS FLAG
FROM (
    SELECT COD_SUCURSAL, DESC_SUCURSAL, 
        CASE 
        WHEN [DESC_SUCURSAL] IS NULL OR [COD_SUCURSAL] IS NULL
        THEN '-1'
        ELSE '1'
        END AS flag,
    ROW_NUMBER() OVER ( PARTITION BY COD_SUCURSAL, DESC_SUCURSAL ORDER BY COD_SUCURSAL DESC) AS rep
    FROM [DW_COMERCIAL].[dbo].STG_DIM_SUCURSAL
) AS SUB

END
