USE [DW_COMERCIAL]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[sp_carga_int_DIM_CATEGORIA]
AS
BEGIN

TRUNCATE TABLE [DW_COMERCIAL].[dbo].[INT_DIM_CATEGORIA] 

INSERT INTO [DW_COMERCIAL].[dbo].[INT_DIM_CATEGORIA] (
   COD_CATEGORIA, DESC_CATEGORIA, Flag
    )

    SELECT COD_CATEGORIA ,DESC_CATEGORIA, 
    CASE 
    WHEN rep > 1 OR flag = '-1' THEN 'N'
    ELSE 'S' 
    END AS FLAG
from (
SELECT COD_CATEGORIA, DESC_CATEGORIA, 
    CASE 
    WHEN [DESC_CATEGORIA] IS NULL OR [COD_CATEGORIA] IS NULL
    THEN '-1'
    ELSE '1'
    END AS flag,
ROW_NUMBER() OVER ( PARTITION BY COD_CATEGORIA, DESC_CATEGORIA ORDER BY COD_CATEGORIA DESC) AS rep
FROM [DW_COMERCIAL].[dbo].[STG_DIM_CATEGORIA] ) as subquery 

END