USE [DW_COMERCIAL]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[sp_carga_DIM_VENDEDOR]
@usu NVARCHAR(10)
AS 
BEGIN

DECLARE @fecha SMALLDATETIME
SET @fecha = GETDATE()

UPDATE DV
SET  DV.[COD_VENDEDOR] = IDV.COD_VENDEDOR
    ,DV.[NOMBRE] = IDV.[NOMBRE]
    ,DV.[APELLIDO] = IDV.[APELLIDO]
    ,DV.FECHA_UPDATE = @fecha
    ,DV.USUARIO_UPDATE = @usu
FROM [DW_COMERCIAL].[dbo].DIM_VENDEDOR AS DV
JOIN [DW_COMERCIAL].[dbo].INT_DIM_VENDEDOR AS IDV 
ON DV.COD_VENDEDOR = IDV.COD_VENDEDOR

INSERT INTO [DW_COMERCIAL].[dbo].DIM_VENDEDOR(
    [COD_VENDEDOR]
    ,[NOMBRE]
    ,[APELLIDO]
    ,[FECHA_ALTA]
    ,[USUARIO_ALTA]
    ,[FECHA_UPDATE]
    ,[USUARIO_UPDATE]
)

SELECT 
     IDV.[COD_VENDEDOR]
    ,IDV.[NOMBRE]
    ,IDV.[APELLIDO]
    ,CASE WHEN FECHA_ALTA IS NULL THEN @fecha
    END
    ,CASE WHEN USUARIO_ALTA IS NULL THEN @usu
    END
    ,@fecha
    ,@usu

FROM [DW_COMERCIAL].[dbo].INT_DIM_VENDEDOR AS IDV
LEFT JOIN [DW_COMERCIAL].[dbo].DIM_VENDEDOR AS DV
ON IDV.COD_VENDEDOR = DV.COD_VENDEDOR
WHERE IDV.FLAG = 'S'
AND DV.COD_VENDEDOR IS NULL

END
