USE [DW_COMERCIAL]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[sp_carga_DIM_CLIENTE]
@usu NVARCHAR(10)
AS 
BEGIN 

DECLARE @fecha SMALLDATETIME
SET @fecha = GETDATE()

UPDATE DC
SET  DC.[NOMBRE] = IDC.NOMBRE
    ,DC.[APELLIDO] = IDC.[APELLIDO]
    ,DC.[COD_CLIENTE] = IDC.COD_CLIENTE
    ,DC.FECHA_UPDATE = @fecha
    ,dc.USUARIO_UPDATE = @usu
FROM [DW_COMERCIAL].[dbo].DIM_CLIENTE AS DC
JOIN [DW_COMERCIAL].[dbo].INT_DIM_CLIENTE AS IDC 
ON DC.COD_CLIENTE = IDC.COD_CLIENTE

INSERT INTO [DW_COMERCIAL].[dbo].DIM_CLIENTE(
    [COD_CLIENTE]
    ,[NOMBRE]
    ,[APELLIDO]
    ,[FECHA_ALTA]
    ,[USUARIO_ALTA]
    ,[FECHA_UPDATE]
    ,[USUARIO_UPDATE]
)

SELECT 
     IDC.[COD_CLIENTE]
    ,IDC.[NOMBRE]
    ,IDC.APELLIDO
    ,CASE WHEN FECHA_ALTA IS NULL THEN @fecha
    END
    ,CASE WHEN USUARIO_ALTA IS NULL THEN @usu
    END
    ,@fecha
    ,@usu

FROM [DW_COMERCIAL].[dbo].INT_DIM_CLIENTE AS IDC
LEFT JOIN [DW_COMERCIAL].[dbo].DIM_CLIENTE AS DC
ON IDC.COD_CLIENTE = DC.COD_CLIENTE
WHERE IDC.FLAG = 'S'
AND DC.COD_CLIENTE IS NULL

END