USE [DW_COMERCIAL]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[sp_carga_FACT_VENTAS]
@usu NVARCHAR(10), @fechainicio SMALLDATETIME, @fechafin SMALLDATETIME
AS 
BEGIN

DECLARE @fecha SMALLDATETIME
SET @fecha = GETDATE()

DELETE FROM [DW_COMERCIAL].[dbo].FACT_VENTAS
WHERE TIEMPO_KEY BETWEEN @fechainicio AND @fechafin

INSERT INTO [DW_COMERCIAL].[dbo].FACT_VENTAS(
[PRODUCTO_KEY]
,[CATEGORIA_KEY]
,[CLIENTE_KEY]
,[PAIS_KEY]
,[VENDEDOR_KEY]
,[SUCURSAL_KEY]
,[TIEMPO_KEY]
,[CANTIDAD_VENDIDA]
,[MONTO_VENDIDO]
,[PRECIO]
,[COMISION_COMERCIAL]
,[FECHA_ALTA]
,[USUARIO_ALTA]
)

SELECT 
    PROD.[PRODUCTO_KEY]
    ,CAT.[CATEGORIA_KEY]
    ,CLI.[CLIENTE_KEY]
    ,PA.[PAIS_KEY]
    ,VEN.[VENDEDOR_KEY]
    ,SUC.[SUCURSAL_KEY]
    ,TP.[TIEMPO_KEY]
    ,IFV.[CANTIDAD_VENDIDA]
    ,IFV.[MONTO_VENDIDO]
    ,IFV.[PRECIO]
    ,IFV.[COMISION_COMERCIAL]
    ,@fecha
    ,@usu

FROM [DW_COMERCIAL].[dbo].INT_FACT_VENTAS AS IFV
JOIN [DW_COMERCIAL].[dbo].DIM_PRODUCTO AS PROD
ON PROD.COD_PRODUCTO = IFV.COD_PRODUCTO
JOIN [DW_COMERCIAL].[dbo].DIM_CATEGORIA AS CAT
ON CAT.COD_CATEGORIA = IFV.COD_CATEGORIA
JOIN [DW_COMERCIAL].[dbo].DIM_CLIENTE AS CLI
ON CLI.COD_CLIENTE = IFV.COD_CLIENTE
JOIN [DW_COMERCIAL].[dbo].DIM_PAIS AS PA 
ON PA.COD_PAIS = IFV.COD_PAIS
JOIN [DW_COMERCIAL].[dbo].DIM_VENDEDOR AS VEN
ON VEN.COD_VENDEDOR = IFV.COD_VENDEDOR
JOIN [DW_COMERCIAL].[dbo].DIM_SUCURSAL AS SUC
ON SUC.COD_SUCURSAL = IFV.COD_SUCURSAL
JOIN [DW_COMERCIAL].[dbo].DIM_TIEMPO AS TP
ON TP.TIEMPO_KEY = IFV.FECHA
WHERE IFV.FLAG = 'S'
AND IFV.Fecha BETWEEN @fechainicio AND @fechafin

END